services:
  - type: web
    name: taalflix-proxy
    env: python
    plan: free
    buildCommand: env -u http_proxy -u https_proxy -u HTTP_PROXY -u HTTPS_PROXY -u all_proxy -u ALL_PROXY pip install -r requirements.txt && curl -fsSL https://deno.land/install.sh | sh
    startCommand: export DENO_INSTALL="$HOME/.deno" && export PATH="$DENO_INSTALL/bin:$PATH" && python yt_proxy.py
    healthCheckPath: /yt/dC6ZGLzdaTs
