services:
  - type: web
    name: taalflix-proxy
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python yt_proxy.py
    healthCheckPath: /yt/dC6ZGLzdaTs
