#!/usr/bin/env python3
"""One command: YouTube URL -> subtitles -> quizzes -> baked into the site.

  python3 scripts/add_video.py "https://www.youtube.com/watch?v=XXXX" [--cefr A2]

What it does:
  1. Extracts the video id + title (yt-dlp, Deck's network).
  2. Fast path: German subtitles -> sentence clips + same-sound trap quizzes
     (+ EN/AR translations when YouTube has them).
  3. Slow path (no subtitles): Whisper sampling on the Deck CPU.
  4. Appends clips (section=myvideos, verified=false) to
     web/myvideos-baked.js + app/web/myvideos-baked.js (deduped by clip_id).
  5. Prints the git commands to put it live (Pages rebuilds in ~1-2 min).

No server, no Render. Run on the Deck where yt-dlp + whisper work.
"""
import json, os, subprocess, sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(HERE, "server"))
sys.path.insert(0, os.path.join(HERE, "worker"))

# Whisper model lives in the system cache; Deck shell has proxy vars that
# break huggingface_hub — neutralize both for this process.
os.environ["HF_HOME"] = "/var/cache/huggingface"
os.environ["HF_HUB_OFFLINE"] = "1"
for k in ("ALL_PROXY", "all_proxy", "http_proxy", "https_proxy",
          "HTTP_PROXY", "HTTPS_PROXY"):
    os.environ.pop(k, None)

import guards  # noqa: E402

YTDLP = os.path.expanduser(os.environ.get("HK_YTDLP", "~/whisperenv/bin/yt-dlp"))
ENV = dict(os.environ)
BAKED = [os.path.join(HERE, "web", "myvideos-baked.js"),
         os.path.join(HERE, "app", "web", "myvideos-baked.js")]


def title_of(vid):
    try:
        return subprocess.run(
            [YTDLP, "--no-warnings", "--print", "%(title)s",
             f"https://www.youtube.com/watch?v={vid}"],
            env=ENV, capture_output=True, text=True, timeout=60).stdout.strip()
    except Exception:
        return vid


def load_vocab():
    for fp in (os.path.join(HERE, "app", "clips_modern_fixed.json"),
               os.path.join(HERE, "app", "clips.json")):
        if os.path.exists(fp):
            try:
                clips = json.load(open(fp, encoding="utf-8"))
                return sorted({w.strip(".,!?…:;«»()\"'") for c in clips
                               for w in c.get("dutch_text", "").split()
                               if 3 <= len(w.strip(".,!?…:;«»()\"'")) <= 18})
            except Exception:
                pass
    return ["Wasser", "Zeit", "Leute"]


def read_baked(fp):
    if not os.path.exists(fp):
        return []
    t = open(fp, encoding="utf-8").read()
    i = t.find("[")
    if i < 0:
        return []
    try:
        return json.loads(t[i:].rstrip().rstrip(";"))
    except Exception:
        return []


def write_baked(fp, clips):
    os.makedirs(os.path.dirname(fp), exist_ok=True)
    blob = json.dumps(clips, ensure_ascii=False, separators=(",", ":"))
    open(fp, "w", encoding="utf-8").write(
        "/* Auto-generated by scripts/add_video.py — personal My videos clips.\n"
        "   Do not hand-edit; append via the script. */\n"
        "window.__SEED_MYVIDEOS = " + blob + ";\n")


def main():
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("urls", nargs="+", help="video or playlist URLs")
    ap.add_argument("--cefr", default="A2")
    ap.add_argument("--max", type=int, default=12)
    ap.add_argument("--section", default="myvideos")
    ap.add_argument("--playlist-max", type=int, default=15)
    args = ap.parse_args()

    # Expand: videos stay, playlists list their items (Deck network).
    queue = []
    for u in args.urls:
        lid = None
        try:
            import urllib.parse, re
            q = urllib.parse.parse_qs(urllib.parse.urlparse(u).query)
            lid = (q.get("list") or [None])[0]
            if lid and not re.fullmatch(r"[A-Za-z0-9_-]{8,64}", lid):
                lid = None
        except Exception:
            pass
        if lid:
            sys.path.insert(0, os.path.join(HERE, "worker"))
            from worker import expand_playlist
            items = expand_playlist(lid, args.playlist_max)
            print(f"Playlist {lid}: {len(items)} videos")
            queue.extend(items)
        else:
            vid, canon_or_err = guards.extract_video_id(u)
            if not vid:
                print(f"Skip {u[:60]}: {canon_or_err}")
                continue
            queue.append((vid, None))
    if not queue:
        raise SystemExit("Nothing usable to add.")

    workdir = os.path.join(HERE, "_clipcache_ingest")
    os.makedirs(workdir, exist_ok=True)
    vocab = load_vocab()

    from pipeline_fastpath import run_fastpath, NoSubtitles
    from whisper_fallback import run_whisper_fallback
    all_clips = []
    for n, (vid, given_title) in enumerate(queue):
        title = given_title or title_of(vid) or vid
        print(f"\n[{n + 1}/{len(queue)}] {title} ({vid})")
        try:
            print("  Fast path: subtitles…")
            clips = run_fastpath(vid, title, workdir, vocab=vocab,
                                 cefr=args.cefr, section=args.section)[:args.max]
        except NoSubtitles:
            print("  No subtitles — Whisper sampling (minutes)…")
            clips = run_whisper_fallback(vid, title, workdir, vocab=vocab,
                                         cefr=args.cefr, max_new=args.max,
                                         section=args.section)
        print(f"  -> {len(clips)} clips")
        all_clips.extend(clips)
    if not all_clips:
        raise SystemExit("No usable clips (music/unclear audio?) — nothing added.")
    clips = all_clips

    n_new = 0
    for fp in BAKED:
        have = read_baked(fp)
        ids = {c.get("clip_id") for c in have}
        for c in clips:
            if c.get("clip_id") not in ids:
                have.append(c)
                ids.add(c["clip_id"])
                n_new += 1 if fp == BAKED[0] else 0
        write_baked(fp, have)
        print(f"  {fp}: {len(have)} clips total")
    print(f"\nDone: +{n_new} new quizzes in section '{args.section}' (unverified, personal).")
    print("Preview one:")
    c = clips[0]
    print(f"  [{c['start_time']}-{c['end_time']}s] {c['dutch_text'][:80]}")
    print("\nTo put it live:\n"
          "  git add web/myvideos-baked.js app/web/myvideos-baked.js\n"
          "  git commit -m \"My videos: <title>\" && git push origin main")


if __name__ == "__main__":
    main()
