package com.hoerklar.app;
import android.app.Activity;
import android.os.Bundle;
import android.view.View;
import android.webkit.WebView;
import android.webkit.WebSettings;
import android.webkit.JavascriptInterface;
import android.webkit.WebResourceRequest;
import android.webkit.WebResourceResponse;
import android.graphics.Color;
import androidx.webkit.WebViewAssetLoader;
import androidx.webkit.WebViewClientCompat;
import org.schabi.newpipe.extractor.NewPipe;
import org.schabi.newpipe.extractor.ServiceList;
import org.schabi.newpipe.extractor.downloader.Downloader;
import org.schabi.newpipe.extractor.downloader.Request;
import org.schabi.newpipe.extractor.downloader.Response;
import org.schabi.newpipe.extractor.exceptions.ReCaptchaException;
import org.schabi.newpipe.extractor.stream.StreamInfo;
import org.schabi.newpipe.extractor.stream.SubtitlesStream;
import java.io.IOException;
import java.net.URL;
import java.util.*;
import javax.net.ssl.HttpsURLConnection;

public class MainActivity extends Activity {
    private WebView wv;

    static class SimpleDownloader extends Downloader {
        @Override
        public Response execute(Request request) throws IOException, ReCaptchaException {
            HttpsURLConnection c = (HttpsURLConnection) new URL(request.url()).openConnection();
            c.setRequestMethod(request.httpMethod());
            if (request.headers() != null) {
                for (Map.Entry<String, List<String>> e : request.headers().entrySet()) {
                    c.setRequestProperty(e.getKey(), String.join(",", e.getValue()));
                }
            }
            if (request.dataToSend() != null) {
                c.setDoOutput(true);
                c.getOutputStream().write(request.dataToSend());
            }
            c.connect();
            String body = "";
            try {
                body = new String(c.getInputStream().readAllBytes(), java.nio.charset.StandardCharsets.UTF_8);
            } catch (Exception e) { body = ""; }
            return new Response(c.getResponseCode(), c.getResponseMessage(), c.getHeaderFields(), body, request.url());
        }
    }

    // JS bridge: let the page fetch YouTube subtitles NATIVELY (no CORS in
    // native code). Page calls HKNative.getSubtitles(url) then
    // HKNative.fetchText(trackUrl). Runs off the UI thread.
    public static class HKBridge {
        private static String jq(String s) {
            if (s == null) return "null";
            return "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"")
                    .replace("\n", "\\n").replace("\r", "\\r") + "\"";
        }

        @JavascriptInterface public String getSubtitles(String videoUrl) {
            try {
                StreamInfo info = StreamInfo.getInfo(videoUrl);
                StringBuilder sb = new StringBuilder("{\"title\":");
                sb.append(jq(info.getName())).append(",\"duration\":").append(info.getDuration()).append(",\"tracks\":[");
                boolean first = true;
                for (SubtitlesStream st : info.getSubtitles()) {
                    if (!first) sb.append(",");
                    first = false;
                    String code = "";
                    try { code = String.valueOf(st.getLanguageTag()); } catch (Exception ignored) {}
                    if (code == null || code.isEmpty() || "null".equals(code)) {
                        try { code = st.getLocale().toLanguageTag(); } catch (Exception ignored) {}
                    }
                    String curl = st.isUrl() ? st.getUrl() : st.getContent();
                    sb.append("{\"lang\":").append(jq(code))
                      .append(",\"auto\":").append(st.isAutoGenerated())
                      .append(",\"format\":").append(jq(String.valueOf(st.getFormat())))
                      .append(",\"url\":").append(jq(curl)).append("}");
                }
                return sb.append("]}").toString();
            } catch (Exception e) {
                return "{\"error\":" + jq(e.toString()) + "}";
            }
        }

        @JavascriptInterface public String fetchText(String url) {
            try {
                Request req = Request.newBuilder().get(url).build();
                Response r = new SimpleDownloader().execute(req);
                String b = r.responseBody();
                if (b == null) return "";
                if (b.length() > 300000) b = b.substring(0, 300000);
                return b;
            } catch (Exception e) {
                return "";
            }
        }

        @JavascriptInterface public String fetchAudioB64(String videoUrl) {
            // Whole-track audio (opus) as base64 for on-device Whisper in
            // the page: JS decodes + slices windows itself. Capped ~12MB.
            try {
                StreamInfo info = StreamInfo.getInfo(videoUrl);
                java.util.List<org.schabi.newpipe.extractor.stream.AudioStream> aud = info.getAudioStreams();
                if (aud == null || aud.isEmpty()) return "";
                org.schabi.newpipe.extractor.stream.AudioStream best = aud.get(0);
                for (org.schabi.newpipe.extractor.stream.AudioStream a : aud) {
                    if (a.getAverageBitrate() > 0 && (best.getAverageBitrate() <= 0
                            || a.getAverageBitrate() < best.getAverageBitrate())) best = a;
                }
                java.net.URL u = new java.net.URL(best.getContent());
                HttpsURLConnection c = (HttpsURLConnection) u.openConnection();
                c.setRequestProperty("User-Agent", "Mozilla/5.0 (Linux; Android 13; Pixel 7) AppleWebKit/537.36 Chrome/124.0.0.0 Mobile Safari/537.36");
                c.setConnectTimeout(20000);
                c.setReadTimeout(60000);
                c.connect();
                java.io.InputStream in = c.getInputStream();
                java.io.ByteArrayOutputStream bos = new java.io.ByteArrayOutputStream();
                byte[] buf = new byte[65536];
                int n, total = 0;
                while ((n = in.read(buf)) > 0) {
                    total += n;
                    if (total > 12 * 1024 * 1024) break;
                    bos.write(buf, 0, n);
                }
                in.close();
                if (total < 20000) return "";
                return android.util.Base64.encodeToString(bos.toByteArray(), android.util.Base64.NO_WRAP);
            } catch (Exception e) {
                return "";
            }
        }
    }

    @Override protected void onCreate(Bundle s) {
        super.onCreate(s);
        try { NewPipe.init(new SimpleDownloader(), new org.schabi.newpipe.extractor.localization.Localization("en","GB")); } catch(Exception e){}
        final WebViewAssetLoader assetLoader = new WebViewAssetLoader.Builder()
                .addPathHandler("/assets/", new WebViewAssetLoader.AssetsPathHandler(this))
                .build();

        wv = new WebView(this);
        wv.setBackgroundColor(Color.parseColor("#0a0e1e"));
        WebSettings ws = wv.getSettings();
        ws.setJavaScriptEnabled(true);
        ws.setDomStorageEnabled(true);
        ws.setMediaPlaybackRequiresUserGesture(false);
        ws.setAllowFileAccess(true);
        ws.setAllowContentAccess(true);
        ws.setAllowFileAccessFromFileURLs(true);
        ws.setAllowUniversalAccessFromFileURLs(true);
        ws.setMixedContentMode(WebSettings.MIXED_CONTENT_COMPATIBILITY_MODE);
        ws.setUserAgentString("Mozilla/5.0 (Linux; Android 13; Pixel 7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Mobile Safari/537.36");

        wv.setWebViewClient(new WebViewClientCompat() {
            @Override public WebResourceResponse shouldInterceptRequest(WebView v, WebResourceRequest r) {
                try{
                    String u=r.getUrl().toString();
                    if(u.contains("localhost:8789/yt/") || u.contains("taalflix.local/yt/") || u.contains("hoerklar.local/yt/") || u.contains("hoerklar.onrender.com/yt/") || u.contains("taalflix.onrender.com/yt/")){
                        String vid=u.substring(u.lastIndexOf("/")+1).split("\\?")[0].split("&")[0];
                        StreamInfo info=StreamInfo.getInfo("https://www.youtube.com/watch?v="+vid);
                        String stream=null;
                        for(org.schabi.newpipe.extractor.stream.VideoStream vs: info.getVideoStreams()){
                            if(vs.getResolution().contains("360") || vs.getResolution().contains("480")){ stream=vs.getContent(); break; }
                        }
                        if(stream==null && !info.getVideoStreams().isEmpty()) stream=info.getVideoStreams().get(0).getContent();
                        if(stream!=null){
                            Map<String,String> h=new HashMap<>();
                            h.put("Location", stream);
                            h.put("Access-Control-Allow-Origin","*");
                            return new WebResourceResponse("text/plain","UTF-8",302,"Found",h,null);
                        }
                    }
                }catch(Exception e){}
                return assetLoader.shouldInterceptRequest(r.getUrl());
            }
            @Override public boolean shouldOverrideUrlLoading(WebView v, WebResourceRequest r) {
                return false;
            }
        });

        wv.setLayerType(View.LAYER_TYPE_HARDWARE, null);
        setContentView(wv);
        wv.addJavascriptInterface(new HKBridge(), "HKNative");
        wv.loadUrl("https://abdomedo2033-code.github.io/HoerKlar/");
    }

    @Override public void onBackPressed() {
        if (wv.canGoBack()) wv.goBack(); else super.onBackPressed();
    }
}
